# Generated by Django 4.2.15 on 2024-08-16 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('tips', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tips',
            new_name='Tip',
        ),
    ]
