# Generated by Django 4.2.15 on 2024-08-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tips', '0002_rename_tips_tip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tip',
            old_name='category',
            new_name='programming_language',
        ),
    ]
